### ISSUE TITLE
[TODO - Seção Home]

### ISSUE THREAD

**Issue by bambokianr** [bambokianr/musii-site#2]
- [ ] bug fix -- ao clicar fora das imagens no carrossel, erro no indexFocused.
- [ ] restart na animação css (LegendCarousel) toda vez que recebe nova prop.
- [ ] comportamento mobile do carrossel: à definir.
