### ISSUE TITLE
[TODO - Header]

### ISSUE THREAD

**Issue by bambokianr** [bambokianr/musii-site#5]
- [ ] definir conteúdo `Header` versão mobile
- [ ] implementar versão mobile
- [ ] ancorar cada seção com o link respectivo do componente
